### ISSUE TITLE
problem when reading bib file with accent characters

### ISSUE THREAD

**Issue by gduh** [jbibtex/jbibtex#16]
I get an exception when I try to read files containing accents characters : 

@incollection{lanselle_sujet_2008,
	address = {Arles},
	edition = {(Actes du séminaire "Metaphore et genre", 2003-2005)},
	title = {Le sujet mutique et la metaphore de la pierre},
	shorttitle = {Le sujet mutique et la metaphore de la pierre},
	booktitle = {Regards sur la metaphore, entre {Orient} et {Occident}},
	publisher = {Picquier},
	author = {Lanselle, Rainier},
	editor = {Sakai, Cecile and Struve, Daniel},
	year = {2008},
	pages = {83--106}
}

Exception in thread "main" org.jbibtex.TokenMgrError: Lexical error at line 1, column 12.  Encountered: "\u00e9" (233), after : ""
	at org.jbibtex.LaTeXParserTokenManager.getNextToken(LaTeXParserTokenManager.java:303)
	at org.jbibtex.LaTeXParser.jj_scan_token(LaTeXParser.java:408)
	at org.jbibtex.LaTeXParser.jj_3R_6(LaTeXParser.java:270)
	at org.jbibtex.LaTeXParser.jj_3_3(LaTeXParser.java:253)
	at org.jbibtex.LaTeXParser.jj_2_3(LaTeXParser.java:242)
	at org.jbibtex.LaTeXParser.String(LaTeXParser.java:190)
	at org.jbibtex.LaTeXParser.Object(LaTeXParser.java:66)
	at org.jbibtex.LaTeXParser.ObjectList(LaTeXParser.java:46)
	at org.jbibtex.LaTeXParser.LaTeX(LaTeXParser.java:21)
	at org.jbibtex.LaTeXParser.parse(LaTeXParser.java:16)
	at de.undercouch.citeproc.bibtex.BibTeXConverter.toItemData(BibTeXConverter.java:161)
	at de.undercouch.citeproc.bibtex.BibTeXConverter.toItemData(BibTeXConverter.java:143)
	at de.undercouch.citeproc.bibtex.BibTeXItemDataProvider.addDatabase(BibTeXItemDataProvider.java:32)
	at com.bkzotero.main.MainZotero.main(MainZotero.java:69)

Thanks for your help.

**Comment by vruusmann** [comment]
It appears that you are using Zotero application, which uses the `java-citeproc` library for BibTeX/LaTeX formatting.

The problem is that the `java-citeproc` library depends on an outdated version of the JBibTeX library (its [buildfile] (https://github.com/michel-kraemer/citeproc-java/blob/master/citeproc-java/build.gradle) imports JBibTeX version `1.0.11`, but the current version is `1.0.15`).

I tested your sample file with the JBibTeX example application `org.jpmml.example.PrintExample` and everything worked fine. So, you should ask the maintainer of the `java-citeproc` library to update the JBibTeX dependency to 1.0.15.

**Comment by gduh** [comment]
I tried to recompile java-citeproc with JBibTeX 1.0.15 in order to solve my problem about the accents.
Now it's ok for accents.

But there are others characters that causes problems. For example the ' character. 
With "d'étude" it's ok, but not with "l’écriture" because the ' character code is not the same.

@incollection{lanselle_comment_2004,
	address = {Paris},
	edition = {(Actes de la journée d'étude "Autour de Saikaku", mars 2002)},
	title = {Comment peut-on être romancier ? {A} propos des conditions de l’écriture romanesque en {Chine} aux alentours du {XVIIe} siècle},
	shorttitle = {Comment peut-on être romancier ?},
	booktitle = {Autour de {Saikaku}, le roman en {Chine} et au {Japon} aux {XVIIe} et {XVIIIe} siècles},
	publisher = {Les Indes savantes, Université Paris 7 Denis-Diderot / Groupe de Recherches sur le Japon en sciences sociales et humaines (GReJa)},
	author = {Lanselle, Rainier},
	editor = {Struve, Daniel},
	year = {2004},
	pages = {95--111}
}

The problem also appears with  蒲, for example  : 

@book{pu_songling_trois_2009,
	address = {Paris},
	series = {"{Sources}" ({Trois} contes de {Pu} {Songling} 蒲松齡, {Liaozhai} zhiyi 聊齋志異 : 11.3 ({Lz}415) « {Shuchi} » 書癡, « {Le} fou des livres » ; 11.4 ({Lz}416) « {Qitian} dasheng » 齊天大聖, « {Le} {Grand}-saint {Egal} du {Ciel} » ; 11.3 ({Lz}417) « {Qingwa} shen » 青蛙神, « {Le} {Dieu} {Grenouille} », présents dans le fragment manuscrit conservé à la {Fondation} {Martin} {Bodmer}, {Genève}. {Vol}. 1 : {Traduction} annotée avec introduction ; vol. 2 : {Fac}.-sim. du fragment de la collection {Bodmer}.)},
	title = {Trois {Contes} étranges},
	shorttitle = {Trois {Contes} étranges},
	abstract = {CR de Durand-Dastès : voir connexe
CR de Porret : voir connexe},
	publisher = {PUF},
	author = {Pu Songling, (Prénom)},
	editor = {Lanselle, Rainier},
	translator = {Lanselle, Rainier},
	year = {2009}
}

**Comment by vruusmann** [comment]
Please excuse my french skills, but aren't you supposed to use the same `\'` character with "d'étude" and "l’écriture"? If not, then what are the Unicode codes for characters that you can legally use as apostrophes?

The BibTeX/LaTeX parsers permit Unicode character ranges as specified in the JavaCC grammar files. For example, the LaTeX grammar file of JBibTeX version 1.0.15 contains the following specification:
`< UNICODE_LETTER : ["\u0100"-"\u1fff", "\u20ac", "\u2122"] >`

The chinese(?) characters are not supported, because they fall outside of the specified range. You can enable them by extending the specification of `UNICODE_LETTER` as needed, rebuilding the JBibTeX library, and adding it to the classpath of your Zotero application.

I am somewhat biased against adding all sorts of extensions and exceptions to BibTeX/LaTeX grammars, because some other BibTeX producer software is doing a bad job. I have explained my reasons for doing so (maybe here in GitHub issues, but more likely in Google Code issues) when such issues have been reported earlier.

My suggestion would be to create a special-purpose java.io.Reader class that can fix all inconsistencies (ie. different variants of the apostrophe) and filter out unsupported characters, so that the BibTeX/LaTeX parsers only see "correct" character data. Alternatively, it would possible to wrap the parsing of individual BibTeX entries and/or LaTeX fields into try-catch statements, so that valid records would be processed normally, and invalid records would be left untouched.

**Comment by gduh** [comment]
The problem with french (and maybe others languages ?) some characters exists with différents codes. The difference between them is the graphical representation. For example : 
-  \'  =  \u0027 is the standard apostrophe. 
-  \’  =  \u2019 is a different graphical representation often used by MS Word but not only

Other example with \" and \« or \»


I'm not expert from BibTex, no more TeX or LaTeX, so just for me to understand when you say : *I am somewhat biased against adding all sorts of extensions and exceptions to BibTeX/LaTeX grammars, because some other BibTeX producer software is doing a bad job.*
As an example, JBibTeX can now parse file containing é character. But in fact the é character in BibTeX file should be encoded with TeX code  \'{e}  right ?  
So, the problem comes from the tools used to create the BibTeX file ?

If your are interesting, I keep you inform what we are going to do about Chinese characters. It's possible we try to modify JBibTex for that. In any cases, I'll have to find a solution.

**Comment by vruusmann** [comment]
Thank your for the clarifications. Let's work together to fix this mess.

I see that the problem with apostrophes is that somebody has been using MS Word to author BibTeX files, and this particular MS Word instance had "replace normal apostrophes with smart apostrophes" configuration option enabled.

Obviously, MS Word users are a big user group, and the JBibTeX library should adapt to their quirks (rather than fight back). I don't have a MS Word instance, so I need your help figuring out Unicode character codes for the following "smart" characters:
 * apostrophe. Is it always `\u2019`?
 * single quote (or is it the same as apostrophe?). Are there different variants of it for "open to the left" and "open to the right" case?
 * double quote, open to the left
 * double quote, open to the right

If you can get me those Unciode character codes, then I will update BibTeX and LaTeX grammars accordingly.

**Comment by gduh** [comment]
With the BibTeX files that I tested : 

apostrophe can be one of the following :
  - the standard code \u0027 (ok with JBibTeX)
  - or \u2019 (Not ok actually with JBibTeX)
It's not always the same code.

Single quote is the same as apostrophe (\u2019). This is a list of Unicode character codes find during my test, including single/double quote :

\u2018  -->  \‘ Left single quotation mark
\u2019  -->  \’ right single quotation mark
\u201c  -->  \“ left double quotation mark
\u201d  -->  \” right double quotation mark
\u202f  -->  \  narrow no-break space  
\u2013  -->  \– en dash
\u2212  -->  \− minus sign
\u2022  -->  \• bullet

Keep me informed if you can include all of those codes or not.
I try to be exhaustive but it's not impossible there are others characters. But I don't hope so, except Chinese characters.

--------------------------------------------------------------

During my tests, I got another exception parsing the following file : 

@book{anon._[zhuoyuanting_zhuren_]_cheval_1999,
	address = {Arles},
	title = {Le cheval de jade. {Quatre} contes chinois du {XVIIe} siècle [{Zhao} shi bei ]},
	shorttitle = {Le cheval de jade. {Quatre} contes chinois du {XVIIe} siècle [{Zhao} shi bei ]},
	publisher = {Philippe Picquier},
	author = {{Anon. [Zhuoyuanting zhuren ]}},
	editor = {Lanselle, Rainier},
	translator = {Lanselle, Rainier},
	year = {1999}
}

Exception in thread "main" org.jbibtex.TokenMgrException: Lexical error at line 40, column 13.  Encountered: "[" (91), after : ""

I think it's not directly a problem with [ or ] Unicode but it's seems to be something else.

**Comment by vruusmann** [comment]
Selected Unicode punctuation characters were enabled in commit c5b6bb72cc. Currently, I did not include the narrow non-break space (`\u202f `) and the bullet (`\u2022`) characters. Maybe will do it later if you can confirm that they are really frequent in real-life BibTeX database files.

You can more characters to LaTeX grammar file as needed.

**Comment by vruusmann** [comment]
Square brackets were enabled in commit df67eaff6d.

You should rebuild the JBibTeX library from the latest source checkout now. The build will produce a JAR file `jbibtex-1.0-SNAPSHOT.jar`, that you should start using in your tweaked version of the Zotero application instead of the JBibTeX version 1.0.15 library.

I will release the new version once you have confirmed that everything works fine.

**Comment by gduh** [comment]
I'm not able to rebuild the library.
I get an error with the classes generated with javacc on TokenMgrException (BibTeXParser.java and LaTeXParser.java). I never use javacc so I'm not sur if I use it correctly to generate the library.

**Comment by vruusmann** [comment]
What is the build error message?

The build is self-contained. The JavaCC dependency `net.java.dev.javacc:javacc:6.1.2` is automatically downloaded from the Maven Central repository if necessary.

By the way, the JBibTeX library is automatically built using the Travis-CI service: [jbibtex/jbibtex] (https://travis-ci.org/jbibtex/jbibtex)

**Comment by gduh** [comment]
Well, I don't use/know Travis, so, after à look, I think all of this is quiet complex to update my environnement to build the project. 
Moreover I will always have the problem with others specials characters and Chinese characters too. 
I'm not sur this is the best way for me. At now, I have no real solution, I need to think about it and try to find how to solve my problem with cite-proc/jbibtex or maybe something else...

**Comment by SheidaV** [comment]
Hi, I have the same errror when it's compiled in a Tomcat Server, but in local it works fine. 

I don't use citeproc, this is the error:
2021-06-22 23:23:26.749 ERROR 11476 --- [nio-8080-exec-6] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/new] due to exception [Lexical error at line 132, column 12.  Encountered: "\u00a9" (169), after : ""]
org.jbibtex.TokenMgrException: Lexical error at line 132, column 12.  Encountered: "\u00a9" (169), after : ""
        at org.jbibtex.BibTeXParserTokenManager.getNextToken(BibTeXParserTokenManager.java:719) ~[jbibtex-1.0.18.jar:na]
        at org.jbibtex.BibTeXParser.jj_scan_token(BibTeXParser.java:1045) ~[jbibtex-1.0.18.jar:na]
        at org.jbibtex.BibTeXParser.jj_3_7(BibTeXParser.java:845) ~[jbibtex-1.0.18.jar:na]
        at org.jbibtex.BibTeXParser.jj_2_7(BibTeXParser.java:821) ~[jbibtex-1.0.18.jar:na]
